"""Gymnasium/SB3 adapters for ALA Pianist."""

from ala_pianist.rl.general_one_hand_env import GeneralOneHandGoalEnv, GeneralRewardConfig
from ala_pianist.rl.droq import (
    CriticEnsemble,
    DroQAgent,
    DroQConfig,
    DroQPolicy,
    ReplayBuffer,
    SquashedGaussianActor,
    load_droq_checkpoint,
    replay_buffer_from_checkpoint,
    restore_rng_state,
)
from ala_pianist.rl.direct_audio_droq import (
    DirectActor,
    DirectDroQAgent,
    DirectDroQConfig,
    IndexedDirectReplayBuffer,
    RawAudioEncoder,
    direct_rng_state_dict,
    indexed_replay_from_checkpoint,
    load_direct_droq_checkpoint,
    restore_direct_rng_state,
    set_direct_droq_seed,
)
from ala_pianist.rl.direct_audio_env import (
    DirectAudioClip,
    DirectAudioGoalEnv,
    DIRECT_AUDIO_EVAL_MODES,
    FORBIDDEN_OBSERVATION_FIELDS,
    PHYSICAL_OBSERVATION_FIELDS,
    build_direct_audio_reference_bank,
)
from ala_pianist.rl.keyset_env import KEYSET_MIDI, KeysetPianoGymEnv, make_keyset_observation
from ala_pianist.rl.residual_env import (
    C_SHARP_5_DIRTY_BASE_ACTION,
    D5_DIRTY_BASE_ACTION,
    D_SHARP_5_DIRTY_BASE_ACTION,
    ResidualSingleNoteEnv,
    get_dirty_base_action,
    get_dirty_csharp5_base_action,
    get_dirty_d5_base_action,
    get_dirty_dsharp5_base_action,
)
from ala_pianist.rl.gym_env import SingleNotePianoGymEnv, write_single_note_rl_midi

__all__ = [
    "D_SHARP_5_DIRTY_BASE_ACTION",
    "C_SHARP_5_DIRTY_BASE_ACTION",
    "D5_DIRTY_BASE_ACTION",
    "KEYSET_MIDI",
    "CriticEnsemble",
    "DroQAgent",
    "DroQConfig",
    "DroQPolicy",
    "DirectActor",
    "DirectAudioClip",
    "DirectAudioGoalEnv",
    "DirectDroQAgent",
    "DirectDroQConfig",
    "DIRECT_AUDIO_EVAL_MODES",
    "FORBIDDEN_OBSERVATION_FIELDS",
    "GeneralOneHandGoalEnv",
    "GeneralRewardConfig",
    "IndexedDirectReplayBuffer",
    "KeysetPianoGymEnv",
    "PHYSICAL_OBSERVATION_FIELDS",
    "RawAudioEncoder",
    "ReplayBuffer",
    "ResidualSingleNoteEnv",
    "SingleNotePianoGymEnv",
    "get_dirty_base_action",
    "get_dirty_csharp5_base_action",
    "get_dirty_d5_base_action",
    "get_dirty_dsharp5_base_action",
    "SquashedGaussianActor",
    "build_direct_audio_reference_bank",
    "direct_rng_state_dict",
    "indexed_replay_from_checkpoint",
    "load_direct_droq_checkpoint",
    "load_droq_checkpoint",
    "make_keyset_observation",
    "replay_buffer_from_checkpoint",
    "restore_rng_state",
    "restore_direct_rng_state",
    "set_direct_droq_seed",
    "write_single_note_rl_midi",
]
